apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: Teste Fullstack Plataforma - DevX.
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: matheusfolsfrwk
  lifecycle: experimental
